# Generated by Django 5.2.16 on 2026-09-10 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveSmallIntegerField()),
                ('wpm', models.PositiveSmallIntegerField()),
                ('accuracy', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wpm'],
            },
        ),
    ]
