# Generated by Django 5.2.16 on 2026-09-13, qo'lda tuzatilgan:
# referral_code avval unique=False holda qo'shiladi, so'ng har bir mavjud
# foydalanuvchiga alohida-alohida noyob kod beriladi, faqat shundan keyin
# unique cheklov qo'yiladi (aks holda bitta umumiy default hammaga tushib,
# UNIQUE constraint buzilardi).

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.users.models import generate_referral_code as _generate_referral_code


def assign_unique_referral_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.referral_code = _generate_referral_code()
        user.save(update_fields=['referral_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_streak_user_last_active_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.RunPython(assign_unique_referral_codes, noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.users.models.generate_referral_code, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
